services:
  postgres:
    image: postgres:14
    container_name: spring-studies-db
    environment:
      POSTGRES_DB: spring_studies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5438:5432"
    command: ["postgres", "-c", "ssl=off"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  spring-network:
    driver: bridge

volumes:
  postgres_data: